library/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('staff/',include('staff.urls'))
]

staff/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
  
    path('book/',views.book, name='book'),
    path('show/',views.show, name='show'),
    path('update/<int:id>/', views.update, name='update'),  
    path('delete/<int:id>/', views.destroy, name='delete'), 
    path('issuedelete/<int:id>/', views.issuedestroy, name='issuedelete'),
    path('issuebook/<int:id>/',views.issuebook, name='issuebook'),
    path('issueshow/',views.issueshow, name='issueshow'),
  path('showuser/',views.showuser, name='showuser'),
  path('userdelete/<str:username>/', views.destroyuser, name='userdelete'),
  path('register/',views.register, name='register'),
  path('editprofile',views.editprofile, name='editprofile'),
  path('',views.home, name='home'),
  path('login_admin/',views.login_admin, name='login_admin'),
  path('logout/',views.logout, name='logout'),
    path('login_user/',views.login_user, name='login_user'),
    path('studentissue/',views.studentissue, name='studentissue'),
    path('changepassword/',views.changepassword, name='changepassword'),
    
    path('userhome/',views.userhome, name='userhome'),
    path('renew/<int:id>/',views.renew, name='renew'),
  path('search',views.search, name='search'),
  path('fine/<int:id>/',views.fine, name='fine'),
  
]

staff/models.py
from django.db import models
from datetime import date, datetime

# Create your models here.
class Book(models.Model):  
    issn = models.CharField(max_length=20)  
    bname = models.CharField(max_length=100)  
    bwritter = models.CharField(max_length=15)  
    class Meta:  
        db_table = "book"  
class IssueBook(models.Model): 
    sname= models.CharField(max_length=100)
    sroll=models.CharField(max_length=100)
    sdept=models.CharField(max_length=100)
    bname = models.CharField(max_length=100)  
    bissn = models.CharField(max_length=15)
    bwritter = models.CharField(max_length=15)
    issue_date=models.DateField(auto_now_add=False,auto_now=False,blank=True,null=True)
    submission_date=models.DateField(auto_now_add=False,auto_now=False,blank=True,null=True)
    class Meta:  
        db_table = "issuebook"  

staff/forms.py
from django import forms  
from .models import Book,IssueBook 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm 

class BookForm(forms.ModelForm):  
    class Meta:  
        model = Book  
        fields = "__all__" 
class IssueBookForm(forms.ModelForm):  
    class Meta:  
        model = IssueBook  
        fields = "__all__" 
class EditprofileForm(UserChangeForm):
    password=None
    class Meta:
        model=User
        fields=['email','first_name','last_name']
        

staff/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User,auth
from django.contrib import messages
from django.http import HttpResponse
from . forms import BookForm,IssueBookForm, EditprofileForm
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from . models import Book,IssueBook
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate,update_session_auth_hash
from datetime import datetime, timedelta
from datetime import date
import datetime
# Create your views here.
def home(request):
    return render(request,"staff/home.html")


def userhome(request):
    return render(request,"staff/userhome.html")


def book(request):
    if request.method=="POST":
        form=BookForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                books=Book.objects.all()
                return render(request,'staff/show.html',{'books':books})
            except:
                pass
    else:
        form=BookForm()
    return render(request,'staff/index.html',{'form':form})  


def show(request):  
    books = Book.objects.all()  
    return render(request,"staff/show.html",{'books':books})


def update(request, id): 
     
    book = Book.objects.get(id=id)  
    form = BookForm(request.POST, instance = book) 
    if form.is_valid():  
        form.save()
        books = Book.objects.all()   
        return render(request,'staff/show.html',{'books':books}) 
    return render(request, 'staff/edit.html', {'book': book})  


def destroy(request, id):  
    book = Book.objects.get(id=id)  
    book.delete()  
    books = Book.objects.all()   
    return render(request,'staff/show.html',{'books':books})
    

def issuebook(request,id):
    x=Book.objects.get(id=id)
    if request.method=="POST":
        form=IssueBookForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                x.delete()
                books=IssueBook.objects.all()
                return render(request,'staff/issueshow.html',{'books':books})
            except:
                pass
    else:
        form=IssueBookForm()
    return render(request,'staff/issueindex.html',{'form':form})


def issuedestroy(request, id):  
    book = IssueBook.objects.get(id=id) 
    x=Book.objects.create(issn=book.bissn,bname=book.bname,bwritter=book.bwritter) 
    x.save()
    book.delete()  
    books = IssueBook.objects.all()   
    return render(request,'staff/issueshow.html',{'books':books}) 

def fine(request, id):
    book=IssueBook.objects.get(id=id)
    p1=datetime.date.today()+timedelta(days=3)
    p2=p1-datetime.date.today()
    d=0
    x=datetime.date.today()-book.submission_date
    
    delta=timedelta(days=1)
    while book.submission_date < datetime.date.today():
        d+=3
        
        book.submission_date += delta
    if x>(book.submission_date-book.submission_date):
        
        book.bname=d
    else:
        
        book.bname=0
        
   
    
     
    return render(request,'staff/fine.html',{'book':book}) 
    


def issueshow(request):  
    books = IssueBook.objects.all()  
    return render(request,"staff/issueshow.html",{'books':books})

def renew(request, id): 
     
    book = IssueBook.objects.get(id=id) 
    form = IssueBookForm(request.POST or None, instance = book) 
    print('out')
    if form.is_valid(): 
        print('in') 
        form.save()
        books = IssueBook.objects.all()   
        return render(request,'staff/issueshow.html',{'books':books}) 
    return render(request, 'staff/renew.html', {'book': book,'form':form})  


def showuser(request):
    User = get_user_model()
    users = User.objects.all()
    return render(request,"staff/showuser.html",{'users':users})


def destroyuser(request, username):
    u = User.objects.get(username=username)  
    u.delete()  
    users = User.objects.all()
    return render(request,"staff/showuser.html",{'users':users})


def register(request):
    if request.method=="POST":
        first_name=request.POST['first_name']
        last_name=request.POST['last_name']
        username=request.POST['username']
        email=request.POST['email']
        password=request.POST['password']
        confirm_password=request.POST['confirm_password']
        if password==confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'username is already exist')
                return redirect(register)
            else:
                user=User.objects.create_user(username=username,password=password,email=email,first_name=first_name,last_name=last_name)
                user.set_password(password)
                user.save()
                return redirect("home")
    else:
        print("this is not post method")
    return render(request,"staff/register.html")


def editprofile(request):
    if request.user.is_authenticated:
        if request.method =="POST":
            form=EditprofileForm(request.POST,instance=request.user)
            if form.is_valid:
                form.save()
                return redirect("userhome")
        else:
            fm=EditprofileForm(instance=request.user)
        return render(request,'staff/useredit.html',{'form':fm})
    else:
        return redirect('login_user')


def login_admin(request):
    if request.method== "POST":
        username=request.POST['username']
        password=request.POST['password']
        
        if username=='admin' and password=='admin':
            
            return redirect('show')
        else:
            print("invalid user")
    return render(request,"staff/admin_login.html")


def logout(request):
    auth.logout(request)
    return redirect('home')


def login_user(request):
    if request.method== "POST":
        username=request.POST['username']
        password=request.POST['password']
        x=auth.authenticate(username=username,password=password)  
        if x is not None:
            auth.login(request,x)
            return render(request,'staff/userhome.html')
        else:
            print("invalid user")
            return HttpResponse("invalid user")
    return render(request,"staff/user_login.html")


def studentissue(request):
    p=request.user.username
    x=IssueBook.objects.raw('SELECT * FROM issuebook WHERE sname=%s',[p])

    return render(request,"staff/studentissue.html",{'x':x})


def changepassword(request):
    if request.user.is_authenticated:
        if request.method =="POST":
            form=PasswordChangeForm(user=request.user, data=request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request,form.user)
                return render(request,'staff/userhome.html')
        else:
           fm=PasswordChangeForm(user=request.user)
        return render(request,'staff/changepassword.html',{'form':fm})
    else:
        return redirect("login_user")

def search(request):
    if request.method =="POST":
        searched=request.POST['searched']
        
        x=Book.objects.filter(bname=searched)
        return render(request,'staff/search.html',{'searched':searched,'x':x})
    else:
        return render(request,'staff/search.html',{})




       

  

templates/staff/admin_login.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Library management system</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar bg-success">
        <div class="container-fluid">
          <span class="navbar-brand mb-0 h1">Library Management System</span>
          <a href = "{% url 'home'  %}">Home</a>
        </div>
      </nav>
    <h1 class="text-center">wellcome to admin  login page</h1>
    <p style="text-align:center;"> <img src="{% static 'image/admin1.jpg' %}" class="center"></p>

    <div class="container-fluid">
      <center>
        <form method="POST" action="{% url 'login_admin' %}" >
            {% csrf_token %}
            <div class="row mb-3">
              <label for="inputEmail3" class="col-sm-2 col-form-label">username</label>
              <div class="col-sm-10">
                <input name="username" type="text" class="form-control" id="">
              </div>
            </div>
            <div class="row mb-3">
              <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
              <div class="col-sm-10">
                <input name="password" type="password" class="form-control" id="inputPassword3">
              </div>
            </div>
    
            <button type="submit" class="btn btn-primary">Log in</button>
          </form>
        </center>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>

templates/staff/changepassword.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Library management system</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar bg-success">
      <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">Library Management System</span>
        <a href = "{% url 'userhome'  %}">Home</a>
        <a href = "{% url 'logout'  %}">LogOut</a>
      </div>
    </nav>
    <h1 class="text-center">well come our library</h1>
    <div class="container-fluid">
        {% if request.user.is_authenticated %}
        <p class="text-success h3"> you are logged in</p>
        <p class="text-success h3">username: {{request.user.username }}</p>
        <center>
        <h1>New password should be 8 characters</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
            
            <p>{{ error }}</p>
            {% endfor %}
            {% endif %}
            {% for x in form %}
            {{x.label_tag}}
            <br>
             {{x}}  <br>
            {% endfor %}
            <br>
            <button type="submit">submit</button>
          </form>
        </center>
  
        {% else %}
        <p class="text-danger h3"> you are not logged in</p>
        <a href="{% url 'register' %}" type="button" class="btn btn-success btn-lg">register</a>
        <a href="{% url 'login_user' %}" type="button" class="btn btn-success btn-lg">log in</a>
        {% endif %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>

templates/staff/edit.html
<!DOCTYPE html>  
{% load static %} 
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
     
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="{% url 'update' book.id %}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">ISSN:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ book.issn }}"/>  
        
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Book Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ book.bname }}" />  
         
    </div>  
  </div>  
 
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Book Writter:</label>  
    <div class="col-sm-4">  
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ book.bwritter }}" />
        
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success" >Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html> 

templates/staff/fine.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar bg-success">
        <div class="container-fluid">
          <span class="navbar-brand mb-0 h1">Library Management System</span>
          <a href = "{% url 'logout'  %}">LogOut</a>
        </div>
      </nav>
      <br>
    <center>
        <h1>Fine</h1>
        <p ><img src="{% static 'image/fine.jpg' %}" alt="image" width="200" height="200"></p>
        {% if book %}
        <p>Total Amount {{book.bname}} 
         Taka</p>
        {% endif %} 
    </center>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</body>
</html>

templates/staff/home.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Library management system</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar bg-success">
        <div class="container-fluid">
          <span class="navbar-brand mb-0 h1">Library Management System</span>
        </div>
      </nav>
    <h1 class="text-center" style="color: blue;">well come our library</h1>
    <p ><img src="{% static 'image/LMS1.jpg' %}" alt="image" width="1300" height="350"></p>
    <div class="container-admin">
      <p><a href="{% url 'login_admin'  %}"><img src="{% static 'image/admin.jpg' %}" style="position: absolute;top: 450px; left: 16px;"></a></p>
  
    </div>
      <div class="container-user">
        <p><a href="{% url 'login_user'  %}"><img src="{% static 'image/student1.jpg' %}" width="200" height="200" style="position: absolute;top: 550px; right: 16px; "></a></p>
  
      </div>
      <div class="container-registration">
        <p ><a href="{% url 'register'  %}" style="position: absolute;top: 8px; right: 16px;">Registration</a></p>
      </div>

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>

templates/staff/index.html

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    
</head>
<body >
    <nav class="navbar bg-success">
        <div class="container-fluid">
          <span class="navbar-brand mb-0 h1">Library Management System</span>
          <span><a href = "{% url 'issueshow'  %}">Issue Book</a></span>
          <a href = "{% url 'showuser'  %}">SHOW THE USERS</a>
          <a href = "{% url 'show'  %}">Available Book</a>
          <a href = "{% url 'logout'  %}">LogOut</a>
        </div>
      </nav>
    <center>
    <h1 style="color: blue;">Add a new Book</h1>
    <br>
    <form id="form-container" method="POST">
        <input type="hidden" name="csrfmiddlewaretoken" value="T7z2VNWSYlzk98MzEc0cgo9sPiycrw0zfzPkJ1hU1g3bC5EMjXOmZvW9enUxXs4c">
       
        <div class="book-form">
        <p>
    <label for="id_issn" style="color: orange;"><h6>Issn:</h6></label>
    <input type="text" name="issn" maxlength="20" required id="id_issn">
  </p>
  <p>
    <label for="id_bname" style="color: orange;"><h6>Bname:</h6></label>
    <input type="text" name="bname" maxlength="100" required id="id_bname">
  </p>
  <p>
    <label for="id_bwritter" style="color: orange;"><h6>Bwritter:</h6></label>
    <input type="text" name="bwritter" maxlength="15" required id="id_bwritter"> 
  </p>
        </div>
        <button type="submit" class="btn btn-success btn-lg">Create Book</button>
    </form>
</center>

    

        <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
       

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

templates/staff/issueshow.html
<!DOCTYPE html> 
{% load static %}   
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Book Records</title>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
    <nav class="navbar bg-success">
        <div class="container-fluid">
          <span class="navbar-brand mb-0 h1">Library Management System</span>
          <span><a href = "{% url 'book'  %}">ADD A NEW Book</a></span>
          <a href = "{% url 'showuser'  %}">SHOW THE USERS</a>
          <a href = "{% url 'show'  %}">Available Book</a>
          <a href = "{% url 'logout'  %}">LogOut</a>
        </div>
      </nav>
    <h1 style="text-align: center;">Issue Book </h1>
<table class="table table-striped table-bordered table-sm" border="2px" align="center">  
    <thead class="thead-dark">  
    <tr>  
        <th>Student Name</th> 
        <th>Student Roll</th>  
        <th>Department Name</th>  
        <th>Book Name</th> 
        <th>Book ISSN</th> 
        <th>Book Writter</th> 
        <th>Book Issue Date</th> 
        <th>Book Submission Date</th> 
        <th>Renew</th> 
        <th>Action</th> 
        <th>Fine</th> 
         
    </tr>  
    </thead>  
    <tbody>  
{% for book in books %}  
    <tr>  
        <td>{{ book.sname }}</td> 
        <td>{{ book.sroll }}</td> 
        <td>{{ book.sdept }}</td>  
        <td>{{ book.bname }}</td>  
        <td>{{ book.bissn}}</td>
        <td>{{ book.bwritter}}</td>  
        <td>{{ book.issue_date}}</td> 
        <td>{{ book.submission_date}}</td> 
        <td>  
            <button type="button" ><a href = "{% url 'renew' book.id %}">Renew</a>  </button>
             
         </td>  
        <td>  
            <button type="button" ><a href = "{% url 'issuedelete' book.id %}">Submit Book</a>  </button>
             
        </td> 
        <td>  
            <button type="button" ><a href = "{% url 'fine' book.id %}">Fine</a>  </button>
             
         </td> 
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  
</body>  
</html> 

templates/staff/register.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Library management system</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar bg-success">
        <div class="container-fluid">
          <span class="navbar-brand mb-0 h1">Library Management System</span>
          <a href = "{% url 'home'  %}">Home</a>
        </div>
      </nav>
    <h1 class="text-center" style="color: gray;">Fill the registration form correctly</h1>
    <div class="container-fluid">
        <form method="POST" action="{% url 'register' %}" class="row g-3" >
            {% csrf_token %}
            <div class="col-md-6">
              <label for="inputEmail4" class="form-label">First name</label>
              <input name="first_name" type="text" class="form-control" id="">
            </div>
            <br>
            <div class="col-md-6">
                <label for="inputEmail4" class="form-label">last name</label>
                <input name="last_name" type="text" class="form-control" id="">
              </div>
              
              <div class="col-md-6">
                <label for="inputEmail4" class="form-label">Email</label>
                <input name="email" type="email" class="form-control" id="inputEmail4">
              </div>
              
              <div class="col-md-6">
                <label for="inputEmail4" class="form-label">user name</label>
                <input name="username" type="text" class="form-control" id="">
              </div>
              
            <div class="col-md-6">
              <label for="inputPassword4" class="form-label">Password</label>
              <input name="password" type="password" class="form-control" id="inputPassword4">
            </div>
            
            <div class="col-md-6">
                <label for="inputPassword4" class="form-label">confirm Password</label>
                <input  name="confirm_password"type="password" class="form-control" id="inputPassword4">
              </div>
             
           
            <div class="col-12">
              <button type="submit" class="btn btn-primary">Register</button>
            </div>
          </form>
          <div class="form-group">
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {% endfor %}
          </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>